apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Starbase
    description: üññüèª Live Long and Prosper
    startUrl: https://homepage.apocalypso.xyz
    background:
        image: https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/3a220e49-b640-4b89-95ad-221f76675213/de9p33m-2629f114-abf3-47e4-b4d8-75dc67530b84.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiIvZi8zYTIyMGU0OS1iNjQwLTRiODktOTVhZC0yMjFmNzY2NzUyMTMvZGU5cDMzbS0yNjI5ZjExNC1hYmYzLTQ3ZTQtYjRkOC03NWRjNjc1MzBiODQucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.c6zcmlOODhMQjG_fl02y91cQDVT6-4rzo97C14k2eJw
        opacity: 25
    theme: dark
    color: neutral
    cardBlur: xs # xs, md, etc... see https://tailwindcss.com/docs/backdrop-blur
    headerStyle: boxedWidgets
    providers:
        openweathermap: ${OPENWEATHERMAP_API_KEY}
        finnhub: ${FINNHUB_API_KEY}
    layout:
        üß∞ Platform Services:
            style: row
            columns: 3
        üè† User Services:
            style: row
            columns: 5
        üõ†Ô∏è Infrastructure Services:
            style: row
            columns: 3
        LoFi Girl:
            style: row
            columns: 3
        Cloud:
            style: row
            columns: 4
        Developer:
            style: row
            columns: 5
        Social:
            style: row
            columns: 6
        Mail:
            style: row
            columns: 2
        Security:
            style: row
            columns: 2
        Reference:
            style: row
            columns: 3
        Freelancing:
            style: row
            columns: 3
        Entertainment:
            style: row
            columns: 2
        Banking:
            style: row
            columns: 2
        Shopping:
            style: row
            columns: 2
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - LoFi Girl:
        - OG:
            - abbr: OG
              icon: mdi-book
              href: https://www.youtube.com/watch?v=jfKfPfyJRdk
        - Synthwave:
            - abbr: SW
              icon: mdi-cosine-wave
              href: https://www.youtube.com/watch?v=4xDzrJKXOOY
        - Asian:
            - abbr: A
              icon: mdi-ideogram-cjk
              href: https://www.youtube.com/watch?v=Na0w3Mz46GA
    - Cloud:
        - iCloud:
            - icon: icloud.png
              href: https://www.icloud.com/
        - Apple:
            - icon: apple.png
              href: https://www.apple.com/
        - Google:
            - icon: google.png
              href: https://www.google.com/
        - Microsoft:
            - icon: microsoft.png
              href: https://www.microsoft.com/en-us/
    - Entertainment:
        - YouTube:
            - abbr: YT
              icon: youtube.png
              href: https://youtube.com/
        - Apple TV:
            - icon: apple.png
              href: https://tv.apple.com/
        - Twitch:
            - icon: twitch.png
              href: https://www.twitch.tv/
        - Xfinity Stream:
            - icon: /icons/xfinity.ico
              href: https://www.xfinity.com/stream/
    - Banking:
        - USAA:
            - icon: si-money
              href: https://usaa.com
        - First Tech FCB:
            - icon: si-money
              href: https://firsttechfed.com
    - Mail:
        - Protonmail:
            - icon: si-proton
              href: https://mail.proton.me/u/0/inbox
        - GMail:
            - icon: gmail.png
              href: https://mail.google.com/mail/u/0/#inbox
        - Outlook:
            - icon: sh-microsoft-outlook.png
              href: https://outlook.live.com/mail/0/inbox
        - iCloud Mail:
            - icon: icloud.png
              href: https://www.icloud.com/mail/
    - Security:
        - 1Password:
            - icon: si-1password
              href: https://my.1password.com/
        - Yubico:
            - icon: si-yubico
              href: https://www.yubico.com/
    - Reference:
        - Wikipedia:
            - icon: wikipedia.png
              href: https://www.wikipedia.org/
        - Raindrop:
            - icon: /icons/raindrop.png
              href: https://app.raindrop.io/
        - ChatGPT:
            - icon: openai.png
              href: https://chatgpt.com/
    - Freelancing:
        - Task Rabbit:
            - icon: /icons/taskrabbit.ico
              href: https://www.taskrabbit.com/
        - Up Work:
            - icon: si-upwork
              href: https://www.upwork.com/
        - Fiverr:
            - icon: si-fiverr
              href: https://www.fiverr.com/
    - Shopping:
        - Gamers Nexus Store:
            - icon: /icons/gamersnexus.ico
              href: https://www.gamersnexus.net/
        - LTT Store:
            - icon: /icons/lttstore.png
              href: https://www.lttstore.com/
    - Developer:
        - GitHub:
            - abbr: GH
              icon: github.png
              href: https://github.com/
        - GitLab:
            - abbr: GL
              icon: gitlab.png
              href: https://gitlab.com/
        - Docker:
            - abbr: D
              icon: docker.png
              href: https://hub.docker.com/
        - Vagrant:
            - icon: sh-hashicorp-vagrant.svg
              href: https://app.vagrantup.com/boxes/search
        - Ansible:
            - icon: ansible.png
              href: https://galaxy.ansible.com/
        - Artifact Hub:
            - icon: si-artifacthub
              href: https://artifacthub.io/
        - Helm:
            - icon: helm.png
              href: https://helm.sh/
        - Stack Overflow:
            - icon: si-stackoverflow
              href: https://stackoverflow.com/
        - Packal:
            - icon: /icons/packal.png
              href: https://www.packal.org/
        - Draw.io:
            - icon: sh-draw-io.png
              href: https://app.diagrams.net/
        - Pictogrammers:
            - icon: /icons/pictogrammers.png
              href: https://pictogrammers.com/library/mdi/
        - Simple Icons:
            - icon: /icons/simpleicons.ico
              href: https://simpleicons.org/
        - Selfhosted Icons:
            - icon: /icons/selfhosted.png
              href: https://selfh.st/icons/
    - Social:
        - sdconrox.com:
            - icon: si-aboutdotme
              href: https://sdconrox.com/
        - About Me:
            - icon: si-aboutdotme
              href: https://about.me/
        - Reddit:
            - icon: reddit.png
              abbr: RE
              href: https://reddit.com/
        - Behance:
            - icon: si-behance
              href: https://www.behance.net/
        - Deviant Art:
            - icon: si-deviantart
              href: https://www.deviantart.com/
        - LinkedIn:
            - icon: linkedin.png
              href: https://www.linkedin.com/
        - Imgur:
            - icon: si-imgur
              href: https://imgur.com/
        - Bluesky:
            - icon: bluesky.png
              href: https://bsky.app/
        - Twitter:
            - icon: twitter.png
              href: https://twitter.com/
        - Instagram:
            - icon: instagram.png
              href: https://www.instagram.com/
        - Facebook:
            - icon: facebook.png
              href: https://www.facebook.com/
        - L1 Tech Forum:
            - icon: /icons/l1.png
              href: https://forum.level1techs.com/
  services.yaml: |
    - üõ†Ô∏è Infrastructure Services:
        - Cloudflare:
            href: https://www.cloudflare.com/
            description: DNS
            icon: cloudflare
        - Namecheap:
            href: https://www.namecheap.com/
            description: DNS
            icon: namecheap
        - Unifi (Public):
            href: https://unifi.sdconrox.com/
            description: Unifi Controller via public route
            icon: unifi
        - Unifi (Private):
            href: https://unifi.sdconrox.com/
            description: Unifi Controller via private route
            icon: unifi
        - Proxmox:
            href: https://proxmox.sdconrox.com/
            description: Proxmox
            icon: proxmox
        - Truenas:
            href: https://truenas.sdconrox.com/
            description: TrueNAS SCALE
            icon: truenas
    - üß∞ Platform Services:
        - ArgoCD:
            href: https://argocd.apocalypso.xyz/
            description: Continuous deployment
            icon: argo-cd
            ping: argocd.apocalypso.xyz
        - Grafana:
            href: https://grafana.apocalypso.xyz/
            description: Metrics and logging across the cluster
            icon: grafana
            ping: grafana.apocalypso.xyz
    - üè† User Services:
        - IT Tools:
            href: https://it-tools.apocalypso.xyz/
            description: An assortment of developer tools
            icon: it-tools
            ping: it-tools.apocalypso.xyz
        - Draw.io:
            href: https://drawio.apocalypso.xyz/
            description: Diagrams
            icon: draw-io
            ping: drawio.apocalypso.xyz
        - Open Speed Test:
            href: https://openspeedtest.apocalypso.xyz/
            description: Test your internet speed
            icon: openspeedtest
            ping: openspeedtest.apocalypso.xyz
        - Open Stirling PDF:
            href: https://pdf.apocalypso.xyz/
            description: Various PDF tools
            icon: stirling-pdf
            ping: pdf.apocalypso.xyz
        - Homebox:
            href: https://homebox.apocalypso.xyz/
            description: A self-hosted home inventory app
            icon: homebox
            ping: homebox.apocalypso.xyz
        - Joplin:
            href: https://joplin.apocalypso.xyz/
            description: A self-hosted note-taking app
            icon: joplin
            ping: joplin.apocalypso.xyz
        - Actual Budget:
            href: https://budget.apocalypso.xyz/
            description: A self-hosted budget app
            icon: actual-budget
            ping: budget.apocalypso.xyz
        - Planka:
            href: https://planka.apocalypso.xyz/
            description: A self-hosted project management app
            icon: planka
            ping: planka.apocalypso.xyz
        - Vikunja:
            href: https://vikunja.apocalypso.xyz/
            description: A self-hosted task management app
            icon: vikunja
            ping: vikunja.apocalypso.xyz
        - FreshRSS:
            href: https://freshrss.apocalypso.xyz/
            description: A self-hosted RSS reader app
            icon: freshrss
            ping: freshrss.apocalypso.xyz
        - Mealie:
            href: https://mealie.apocalypso.xyz/
            description: A self-hosted meal planning app
            icon: mealie
            ping: mealie.apocalypso.xyz
        - OctoPrint:
            href: https://octoprint.apocalypso.xyz/
            description: A self-hosted 3D printing app
            icon: octoprint
            ping: octoprint.apocalypso.xyz
        - Karakeep:
            href: https://karakeep.apocalypso.xyz/
            description: A self-hosted password manager app
            icon: karakeep
            ping: karakeep.apocalypso.xyz
        - Homarr:
            href: https://homarr.apocalypso.xyz/
            description: Another homepage app, but for the arr ecosystem
            icon: homarr
            ping: homarr.apocalypso.xyz
  widgets.yaml: |
    - openweathermap:
        label: Inwood
        units: imperial # or metric
        latitude: 39.364916
        longitude: -78.006818
        provider: openweathermap
    - unifi_console:
        url: https://underverse.sdconrox.com
        key: ${UNIFI_API_KEY} # required if using API key instead of username/password
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - stocks:
        provider: finnhub
        color: true # optional, defaults to true
        cache: 1 # optional, default caches results for 1 minute
        watchlist:
          - DJIA
          - NDAQ
          - AAPL
          - NVDA
          - MSFT
          - TSM
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: long
    - search:
        provider: [google, duckduckgo]
        focus: true
        showSearchSuggestions: true
        target: _blank
  docker.yaml: ""
