apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - üß∞ Platform Services:
        - Kubernetes Dashboard:
            href: https://dashboard.apocalypso.xyz/
            description: Kubernetes Dashboard
            icon: kubernetes
        - ArgoCD:
            href: https://argocd.apocalypso.xyz/
            description: Continuous deployment
            icon: argo
        - Grafana:
            href: https://grafana.apocalypso.xyz/
            description: Metrics and logging across the cluster
            icon: grafana
    - üè† User Services:
        - IT Tools:
            href: https://it-tools.apocalypso.xyz/
            description: An assortment of developer tools
            icon: it-tools
        - Draw.io:
            href: https://drawio.apocalypso.xyz/
            description: Diagrams
            icon: diagrams
        - Open Speed Test:
            href: https://openspeedtest.apocalypso.xyz/
            description: Test your internet speed
            icon: openspeedtest
        - Open Stirling PDF:
            href: https://pdf.apocalypso.xyz/
            description: Various PDF tools
            icon: stirling-pdf
        - Homarr:
            href: https://homarr.apocalypso.xyz/
            description: Another homepage app, but for the arr ecosystem
            icon: homarr
        - Homebox:
            href: https://homebox.apocalypso.xyz/
            description: A self-hosted home inventory app
            icon: homebox
        - Calibre:
            href: https://calibre.apocalypso.xyz/
            description: A self-hosted ebook library
            icon: calibre
    - üõ†Ô∏è Ingrastructure Services:
        - Proxmox:
            href: https://proxmox.sdconrox.com/
            description: Proxmox
            icon: proxmox
  widgets.yaml: |
    - search:
        provider: google
        target: _blank
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
  docker.yaml: ""
