apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Starbase
    description: üññüèª Live Long and Prosper
    background:
        image: https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/68a5fa5a-b297-40cf-94b1-28ccb92931f8/djzmq3x-9ad83875-ab91-4caf-8353-d17ff62ca30c.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiIvZi82OGE1ZmE1YS1iMjk3LTQwY2YtOTRiMS0yOGNjYjkyOTMxZjgvZGp6bXEzeC05YWQ4Mzg3NS1hYjkxLTRjYWYtODM1My1kMTdmZjYyY2EzMGMucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.Cj16L7HJffAizfTNbRm9PRJg6Ij_nYBrv2qHXTCF7EY
        opacity: 25
    theme: dark
    color: neutral
    cardBlur: xs # xs, md, etc... see https://tailwindcss.com/docs/backdrop-blur
    headerStyle: boxed
    providers:
        openweathermap: ${OPENWEATHERMAP_API_KEY}
        finnhub: ${FINNHUB_API_KEY}
    layout:
        Platform Services:
            style: row
            columns: 3
        User Services:
            style: row
            columns: 5
        Ingrastructure Services:
            style: row
            columns: 3
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - LoFi Girl:
        - OG:
            - abbr: OG
              icon: mdi-book
              href: https://www.youtube.com/watch?v=jfKfPfyJRdk
        - Synthwave:
            - abbr: SW
              icon: mdi-cosine-wave
              href: https://www.youtube.com/watch?v=4xDzrJKXOOY
        - Asian:
            - abbr: A
              icon: mdi-ideogram-cjk
              href: https://www.youtube.com/watch?v=Na0w3Mz46GA
    - Cloud:
        - iCloud:
            - icon: icloud.png
              href: https://www.icloud.com/
        - Apple:
            - icon: apple.png
              href: https://www.apple.com/
        - Google:
            - icon: google.png
              href: https://www.google.com/
        - Microsoft:
            - icon: microsoft.png
              href: https://www.microsoft.com/en-us/
    - Entertainment:
        - YouTube:
            - abbr: YT
              icon: youtube.png
              href: https://youtube.com/
        - Apple TV:
            - icon: apple.png
              href: https://tv.apple.com/
        - Twitch:
            - icon: twitch.png
              href: https://www.twitch.tv/
        - Xfinity Stream:
            - icon: /icons/xfinity.ico
              href: https://www.xfinity.com/stream/
    - Banking:
        - USAA:
            - icon: si-money
              href: https://usaa.com
        - First Tech FCB:
            - icon: si-money
              href: https://firsttechfed.com
    - Mail:
        - Protonmail:
            - icon: si-proton
              href: https://mail.proton.me/u/0/inbox
        - GMail:
            - icon: gmail.png
              href: https://mail.google.com/mail/u/0/#inbox
        - Outlook:
            - icon: sh-microsoft-outlook.png
              href: https://outlook.live.com/mail/0/inbox
        - iCloud Mail:
            - icon: icloud.png
              href: https://www.icloud.com/mail/
    - Security:
        - 1Password:
            - icon: si-1password
              href: https://my.1password.com/
        - Yubico:
            - icon: si-yubico
              href: https://www.yubico.com/
    - Reference:
        - Wikipedia:
            - icon: wikipedia.png
              href: https://www.wikipedia.org/
        - Raindrop:
            - icon: /icons/raindrop.png
              href: https://app.raindrop.io/
        - ChatGPT:
            - icon: openai.png
              href: https://chatgpt.com/
    - Freelancing:
        - Task Rabbit:
            - icon: /icons/taskrabbit.ico
              href: https://www.taskrabbit.com/
        - Up Work:
            - icon: si-upwork
              href: https://www.upwork.com/
        - Fiverr:
            - icon: si-fiverr
              href: https://www.fiverr.com/
    - Shopping:
        - Gamers Nexus Store:
            - icon: /icons/gamersnexus.ico
              href: https://www.gamersnexus.net/
        - LTT Store:
            - icon: /icons/lttstore.png
              href: https://www.lttstore.com/
    - Developer:
        - Namecheap:
            - abbr: NC
              icon: namecheap.png
              href: https://www.namecheap.com/
        - GitHub:
            - abbr: GH
              icon: github.png
              href: https://github.com/
        - GitLab:
            - abbr: GL
              icon: gitlab.png
              href: https://gitlab.com/
        - Docker:
            - abbr: D
              icon: docker.png
              href: https://hub.docker.com/
        - Vagrant:
            - icon: sh-hashicorp-vagrant.svg
              href: https://app.vagrantup.com/boxes/search
        - Ansible:
            - icon: ansible.png
              href: https://galaxy.ansible.com/
        - Artifact Hub:
            - icon: si-artifacthub
              href: https://artifacthub.io/
        - Helm:
            - icon: helm.png
              href: https://helm.sh/
        - Stack Overflow:
            - icon: si-stackoverflow
              href: https://stackoverflow.com/
        - Packal:
            - icon: /icons/packal.png
              href: https://www.packal.org/
        - Draw.io:
            - icon: sh-draw-io.png
              href: https://app.diagrams.net/
        - Pictogrammers:
            - icon: /icons/pictogrammers.png
              href: https://pictogrammers.com/library/mdi/
        - Simple Icons:
            - icon: /icons/simpleicons.ico
              href: https://simpleicons.org/
        - Selfhosted Icons:
            - icon: /icons/selfhosted.png
              href: https://selfh.st/icons/
    - Social:
        - sdconrox.com:
            - icon: si-aboutdotme
              href: https://sdconrox.com/
        - About Me:
            - icon: si-aboutdotme
              href: https://about.me/
        - Reddit:
            - icon: reddit.png
              abbr: RE
              href: https://reddit.com/
        - Behance:
            - icon: si-behance
              href: https://www.behance.net/
        - Deviant Art:
            - icon: si-deviantart
              href: https://www.deviantart.com/
        - LinkedIn:
            - icon: linkedin.png
              href: https://www.linkedin.com/
        - Imgur:
            - icon: si-imgur
              href: https://imgur.com/
        - Bluesky:
            - icon: bluesky.png
              href: https://bsky.app/
        - Twitter:
            - icon: twitter.png
              href: https://twitter.com/
        - Instagram:
            - icon: instagram.png
              href: https://www.instagram.com/
        - Facebook:
            - icon: facebook.png
              href: https://www.facebook.com/
        - L1 Tech Forum:
            - icon: /icons/l1.png
              href: https://forum.level1techs.com/
  services.yaml: |
    - üß∞ Platform Services:
        - Kubernetes Dashboard:
            href: https://dashboard.apocalypso.xyz/
            description: Kubernetes Dashboard
            icon: kubernetes
        - ArgoCD:
            href: https://argocd.apocalypso.xyz/
            description: Continuous deployment
            icon: argo-cd
        - Grafana:
            href: https://grafana.apocalypso.xyz/
            description: Metrics and logging across the cluster
            icon: grafana
    - üè† User Services:
        - IT Tools:
            href: https://it-tools.apocalypso.xyz/
            description: An assortment of developer tools
            icon: it-tools
        - Draw.io:
            href: https://drawio.apocalypso.xyz/
            description: Diagrams
            icon: draw-io
        - Open Speed Test:
            href: https://openspeedtest.apocalypso.xyz/
            description: Test your internet speed
            icon: openspeedtest
        - Open Stirling PDF:
            href: https://pdf.apocalypso.xyz/
            description: Various PDF tools
            icon: stirling-pdf
        - Homarr:
            href: https://homarr.apocalypso.xyz/
            description: Another homepage app, but for the arr ecosystem
            icon: homarr
        - Homebox:
            href: https://homebox.apocalypso.xyz/
            description: A self-hosted home inventory app
            icon: homebox
        - Joplin:
            href: https://joplin.apocalypso.xyz/
            description: A self-hosted note-taking app
            icon: joplin
        - Actual Budget:
            href: https://actualbudget.apocalypso.xyz/
            description: A self-hosted budget app
            icon: actual-budget
        - Planka:
            href: https://planka.apocalypso.xyz/
            description: A self-hosted project management app
            icon: planka
        - Vikunja:
            href: https://vikunja.apocalypso.xyz/
            description: A self-hosted task management app
            icon: vikunja
        - FreshRSS:
            href: https://freshrss.apocalypso.xyz/
            description: A self-hosted RSS reader app
            icon: freshrss
        - Mealie:
            href: https://mealie.apocalypso.xyz/
            description: A self-hosted meal planning app
            icon: mealie
        - OctoPrint:
            href: https://octoprint.apocalypso.xyz/
            description: A self-hosted 3D printing app
            icon: octoprint
        - Karakeep:
            href: https://karakeep.apocalypso.xyz/
            description: A self-hosted password manager app
            icon: karakeep
    - üõ†Ô∏è Ingrastructure Services:
        - Proxmox:
            href: https://proxmox.sdconrox.com/
            description: Proxmox
            icon: proxmox
  widgets.yaml: |
    - search:
        provider: google
        target: _blank
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: false
          cpu: true
          memory: true
          showLabel: true
  docker.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
