apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Platform Services:
        - Kubernetes Dashboard:
            href: https://dashboard.apocalypso.xyz/
            description: Kubernetes Dashboard
            icon: kubernetes
        - ArgoCD:
            href: https://argocd.apocalypso.xyz/
            description: Continuous deployment
            icon: argocd
        - Grafana:
            href: https://grafana.apocalypso.xyz/
            description: Metrics and logging across the cluster
            icon: grafana
    - User Services:
        - IT Tools:
            href: https://it-tools.apocalypso.xyz/
            description: An assortment of developer tools
            icon: it-tools
        - Drawi.io:
            href: https://drawio.apocalypso.xyz/
            description: Diagrams
            icon: drawio
        - Open Speed Test:
            href: https://openspeedtest.apocalypso.xyz/
            description: Test your internet speed
            icon: speedtest
    - Ingrastructure Services:
        - Proxmox:
            href: https://proxmox.sdconrox.com/
            description: Proxmox
            icon: proxmox
  widgets.yaml: |
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
  docker.yaml: ""
