apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Starbase
    description: üññüèª Live Long and Prosper
    background:
        image: https://www.deviantart.com/celestin0/art/Starbase-Yorktown-1208704173
        opacity: 25
    theme: dark
    color: neutral
    cardBlur: xs # xs, md, etc... see https://tailwindcss.com/docs/backdrop-blur
    headerStyle: boxed
    providers:
        openweathermap: ${OPENWEATHERMAP_API_KEY}
        finnhub: ${FINNHUB_API_KEY}
    layout:
        Platform Services:
            style: row
            columns: 3
        User Services:
            style: row
            columns: 5
        Ingrastructure Services:
            style: row
            columns: 3
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - üß∞ Platform Services:
        - Kubernetes Dashboard:
            href: https://dashboard.apocalypso.xyz/
            description: Kubernetes Dashboard
            icon: kubernetes
        - ArgoCD:
            href: https://argocd.apocalypso.xyz/
            description: Continuous deployment
            icon: argo-cd
        - Grafana:
            href: https://grafana.apocalypso.xyz/
            description: Metrics and logging across the cluster
            icon: grafana
    - üè† User Services:
        - IT Tools:
            href: https://it-tools.apocalypso.xyz/
            description: An assortment of developer tools
            icon: it-tools
        - Draw.io:
            href: https://drawio.apocalypso.xyz/
            description: Diagrams
            icon: draw-io
        - Open Speed Test:
            href: https://openspeedtest.apocalypso.xyz/
            description: Test your internet speed
            icon: openspeedtest
        - Open Stirling PDF:
            href: https://pdf.apocalypso.xyz/
            description: Various PDF tools
            icon: stirling-pdf
        - Homarr:
            href: https://homarr.apocalypso.xyz/
            description: Another homepage app, but for the arr ecosystem
            icon: homarr
        - Homebox:
            href: https://homebox.apocalypso.xyz/
            description: A self-hosted home inventory app
            icon: homebox
        - Joplin:
            href: https://joplin.apocalypso.xyz/
            description: A self-hosted note-taking app
            icon: joplin
        - Actual Budget:
            href: https://actualbudget.apocalypso.xyz/
            description: A self-hosted budget app
            icon: actual-budget
        - Planka:
            href: https://planka.apocalypso.xyz/
            description: A self-hosted project management app
            icon: planka
        - Vikunja:
            href: https://vikunja.apocalypso.xyz/
            description: A self-hosted task management app
            icon: vikunja
        - FreshRSS:
            href: https://freshrss.apocalypso.xyz/
            description: A self-hosted RSS reader app
            icon: freshrss
        - Mealie:
            href: https://mealie.apocalypso.xyz/
            description: A self-hosted meal planning app
            icon: mealie
        - OctoPrint:
            href: https://octoprint.apocalypso.xyz/
            description: A self-hosted 3D printing app
            icon: octoprint
        - Karakeep:
            href: https://karakeep.apocalypso.xyz/
            description: A self-hosted password manager app
            icon: karakeep
    - üõ†Ô∏è Ingrastructure Services:
        - Proxmox:
            href: https://proxmox.sdconrox.com/
            description: Proxmox
            icon: proxmox
  widgets.yaml: |
    - search:
        provider: google
        target: _blank
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: false
          cpu: true
          memory: true
          showLabel: true
  docker.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
