apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Starbase
    description: üññüèª Live Long and Prosper
    background:
        image: https://www.deviantart.com/celestin0/art/Starbase-Yorktown-1208704173
        opacity: 25
    theme: dark
    color: neutral
    cardBlur: xs # xs, md, etc... see https://tailwindcss.com/docs/backdrop-blur
    headerStyle: boxed
    providers:
        openweathermap: ${OPENWEATHERMAP_API_KEY}
        finnhub: ${FINNHUB_API_KEY}
    layout:
        Platform Services:
            style: row
            columns: 3
        User Services:
            style: row
            columns: 5
        Ingrastructure Services:
            style: row
            columns: 3
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  widgets.yaml: |
    - search:
        provider: google
        target: _blank
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "starbase"
        nodes:
          show: false
          cpu: true
          memory: true
          showLabel: true
