apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drawio
  namespace: drawio
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: User Services
    gethomepage.dev/name: Draw.io
    gethomepage.dev/icon: draw-io
    gethomepage.dev/description: Diagrams
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    external-dns.alpha.kubernetes.io/controller: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - drawio.apocalypso.xyz
      secretName: drawio-tls
  rules:
    - host: drawio.apocalypso.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: drawio
                port:
                  number: 80
