apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.2.0/deploy/rbac-csi-nfs-controller.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.2.0/deploy/csi-nfs-driverinfo.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.2.0/deploy/csi-nfs-controller.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.2.0/deploy/rbac-csi-nfs-node.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.2.0/deploy/csi-nfs-node.yaml
  - storageclass.yaml
images:
  - name: registry.k8s.io/sig-storage/nfsplugin
    newTag: v4.2.0
