apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freshrss
  namespace: freshrss
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: User Services
    gethomepage.dev/name: FreshRSS
    gethomepage.dev/icon: freshrss
    gethomepage.dev/description: RSS Reader
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    external-dns.alpha.kubernetes.io/controller: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - freshrss.apocalypso.xyz
      secretName: freshrss-tls
  rules:
    - host: freshrss.apocalypso.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: freshrss
                port:
                  number: 80
