apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform/onepassword-connect-application.yaml
  - platform/onepassword-secrets-application.yaml
  - platform/nfs-provisioner-application.yaml
  - platform/metallb-application.yaml
  - platform/ingress-nginx-application.yaml
  - platform/external-dns-application.yaml
  - platform/cert-manager-application.yaml
  - platform/cert-manager-issuers-application.yaml
  - platform/kube-prometheus-stack-application.yaml
  - platform/loki-application.yaml
  - platform/promtail-application.yaml
  - platform/cloudflared-application.yaml
  - platform/velero-application.yaml
  - platform/velero-schedule-application.yaml
  - apps/homepage-application.yaml
  - apps/it-tools-application.yaml
  - apps/drawio-application.yaml
  - apps/openspeedtest-application.yaml

  # - apps/homarr-application.yaml
  # - apps/homebox-application.yaml

  # - apps/stirling-pdf-application.yaml

  # - apps/actual-budget-application.yaml
  # - apps/vikunja-application.yaml
  # - apps/planka-application.yaml
  # - apps/freshrss-application.yaml
  # - apps/joplin-application.yaml
  # - apps/mealie-application.yaml
  # - apps/octoprint-application.yaml
  # - apps/karakeep-application.yaml
