apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform/metallb-application.yaml
  - platform/ingress-nginx-application.yaml
  - platform/cert-manager-application.yaml
  - platform/external-dns-application.yaml
  - apps/kubernetes-dashboard-application.yaml
