apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: joplin
  namespace: joplin
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: User Services
    gethomepage.dev/name: Joplin
    gethomepage.dev/icon: joplin
    gethomepage.dev/description: Note Taking
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    external-dns.alpha.kubernetes.io/controller: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - joplin.apocalypso.xyz
      secretName: joplin-tls
  rules:
    - host: joplin.apocalypso.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: joplin
                port:
                  number: 80
