apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vikunja
  namespace: vikunja
  annotations:
    gethomepage.dev/description: Task Management
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: User Services
    gethomepage.dev/icon: vikunja
    gethomepage.dev/name: Vikunja
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    external-dns.alpha.kubernetes.io/controller: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - vikunja.apocalypso.xyz
      secretName: vikunja-tls
  rules:
    - host: vikunja.apocalypso.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vikunja
                port:
                  number: 80
