apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: it-tools
  namespace: it-tools
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: User Services
    gethomepage.dev/name: IT Tools
    gethomepage.dev/icon: it-tools
    gethomepage.dev/description: IT Tools
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    external-dns.alpha.kubernetes.io/controller: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - it-tools.apocalypso.xyz
      secretName: it-tools-tls
  rules:
    - host: it-tools.apocalypso.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: it-tools
                port:
                  number: 80
