apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-dns-secret.yaml
  - cloudflared-secret.yaml
  - cert-manager-secret.yaml
  - grafana-secret.yaml
  - velero-storj-secret.yaml
