apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-csi-driver
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-81"
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    chart: csi-driver-nfs
    targetRevision: 4.12.1
    helm:
      values: |
        kubeletDir: /var/lib/kubelet
        driver:
          name: nfs.csi.k8s.io
        storageClass:
          create: true
          name: nfs-csi
          annotations:
            storageclass.kubernetes.io/is-default-class: "false"
          parameters:
            server: 10.60.0.6
            share: /mnt/sdx-pool-0/sdx-starbase
          mountOptions:
            - nfsvers=4.1
            - rsize=1048576
            - wsize=1048576
            - hard
            - timeo=600
            - retrans=2
          reclaimPolicy: Retain
          volumeBindingMode: Immediate
          allowVolumeExpansion: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
