apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-connect
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://1password.github.io/connect-helm-charts
    chart: connect
    targetRevision: 1.15.1
    helm:
      values: |
        connect:
          credentials:
            existingSecret: op-credentials
        operator:
          enabled: true
          token:
            existingSecret: onepassword-token
  destination:
    server: https://kubernetes.default.svc
    namespace: onepassword-connect
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
